// Client-only extension of server/shared/const.js

CONST.WIDTH = 256;
CONST.HEIGHT = 161;

CONST.MIN_FRAME_DELTA = 5;
CONST.MAX_FRAME_DELTA = 250;

CONST.UI_WIDTH_NAME = 40;

CONST.KEY_BACKSPACE = 8;
CONST.KEY_TAB = 9;
CONST.KEY_ENTER = 13;
CONST.KEY_ESCAPE = 27;
CONST.KEY_LEFT = 37;
CONST.KEY_UP = 38;
CONST.KEY_RIGHT = 39;
CONST.KEY_DOWN = 40;
CONST.KEY_MUTE = 77; // M
CONST.KEY_START = 83; // S

CONST.EVENT_KEYPRESS = 'keypress';
CONST.EVENT_KEYDOWN = 'keydown';
CONST.EVENT_KEYUP = 'keyup';

CONST.DIRECTION_LEFT = 0;
CONST.DIRECTION_UP = 1;
CONST.DIRECTION_RIGHT = 2;
CONST.DIRECTION_DOWN = 3;

CONST.MENU_LEFT = 42;
CONST.MENU_TOP = 48;
CONST.MENU_WIDTH = 167;
CONST.MENU_WRAP = 176;
CONST.MENU_TITLE_HEIGHT = 20;

CONST.GAME_LEFT = 2;
CONST.GAME_TOP = 2;
CONST.GAME_TILE = 4;

CONST.HASH_ROOM = 'room';

CONST.NS_FLOW = 'FLW';
CONST.NS_CHAT = 'CHT';
CONST.NS_DIALOG = 'DLG';
CONST.NS_INPUT = 'INP';
CONST.NS_GAME = 'GAM';
CONST.NS_ROOM = 'ROM';
CONST.NS_SCORE = 'SCR';
CONST.NS_SNAKE = 'SNK';
CONST.NS_SOCKET = 'SOK';
CONST.NS_SPAWN = 'SPN';
CONST.NS_STAGES = 'STG';

CONST.PUB_GAME_TICK = 'TIK';
CONST.PUB_FOCUS_CHANGE = 'FCH';
CONST.PUB_FONT_LOAD = 'FLD';

CONST.STORAGE_MUTE = 'MUT';
CONST.STORAGE_NAME = 'NME';
CONST.STORAGE_XSS = 'XSS';
CONST.STORAGE_COLOR = 'CLR';
CONST.STORAGE_PREFS = 'PRF';

CONST.UC_ARR_LEFT = '\u2190';
CONST.UC_ARR_UP = '\u2191';
CONST.UC_ARR_RIGHT = '\u2192';
CONST.UC_ARR_DOWN = '\u2193';
CONST.UC_ELECTRIC = '\u2301';
CONST.UC_HOURGLASS = '\u231B';
CONST.UC_ENTER_KEY = '\u23ce';
CONST.UC_SQUARE = '\u25a0';
CONST.UC_TR_LEFT = '\u25c0';
CONST.UC_TR_RIGHT = '\u25b6';
CONST.UC_TR_UP = '\u25b2';
CONST.UC_TR_DOWN = '\u25bc';
CONST.UC_BULLSEYE = '\u25ce';
CONST.UC_SKULL = '\u2620';
CONST.UC_FROWNY_FACE = '\u2639';
CONST.UC_HAPPY_FACE = '\u263A';
CONST.UC_HEART = '\u2665';
