xss.EVENT_COMBI = 'C';
xss.EVENT_CHAT_NOTICE = 'CN';
xss.EVENT_CHAT_MESSAGE = 'CM';
xss.EVENT_GAME_COUNTDOWN = 'GC';
xss.EVENT_GAME_DESPAWN = 'GD';
xss.EVENT_GAME_START = 'GS';
xss.EVENT_GAME_STATE = 'GS2';
xss.EVENT_GAME_SPAWN = 'GS3';
xss.EVENT_PING = 'P';
xss.EVENT_PONG = 'PR';
xss.EVENT_ROOM_JOIN = 'RJ';
xss.EVENT_ROOM_MATCH = 'RM';
xss.EVENT_ROOM_SERIALIZE = 'RS';
xss.EVENT_ROOM_START = 'RS2';
xss.EVENT_ROOM_STATUS = 'RS3';
xss.EVENT_SCORE_UPDATE = 'SU';
xss.EVENT_SNAKE_ACTION = 'SA';
xss.EVENT_SNAKE_CRASH = 'SC';
xss.EVENT_SNAKE_SIZE = 'SS';
xss.EVENT_SNAKE_SPEED = 'SS2';
xss.EVENT_SNAKE_UPDATE = 'S';
xss.EVENT_XSS_REQ = 'XS?';
xss.EVENT_XSS_RES = 'XS!';

xss.SERVER_TICK = 'T';

xss.ROOM_KEY_LENGTH = 5;
xss.ROOM_CAPACITY = 6;

xss.ROUNDS_MAX = 3;
xss.ROOM_WIN_BY_MIN = 2;

xss.TIME_ROUND_PAUSE = 2;
xss.TIME_ROUND_GLOAT = 5;
xss.TIME_ALL_ROUNDS_GLOAT = 10;
xss.TIME_ROUND_COUNTDOWN = 3;

xss.SPAWN_SOMETHING_EVERY = [20, 60];
xss.SPAWN_CHANCE_APPLE = 0.9;

xss.SNAKE_SPEED = 120;
xss.SNAKE_SIZE = 4;

xss.FIELD_NAME = 'NM';
xss.FIELD_MAX_PLAYERS = 'MP';
xss.FIELD_DIFFICULTY = 'LD';
xss.FIELD_POWERUPS = 'PU';
xss.FIELD_PRIVATE = 'PV';
xss.FIELD_XSS = 'XS';

xss.FIELD_VALUE_EASY = 1;
xss.FIELD_VALUE_MEDIUM = 2;
xss.FIELD_VALUE_HARD = 3;

xss.ROOM_INVALID = 1;
xss.ROOM_FULL = 2;
xss.ROOM_NOT_FOUND = 3;
xss.ROOM_IN_PROGRESS = 4;

xss.CRASH_WALL = 1;
xss.CRASH_MOVING_WALL = 2;
xss.CRASH_SELF = 3;
xss.CRASH_OPPONENT = 4;
xss.CRASH_OPPONENT_DRAW = 5;

xss.NETCODE_PING_INTERVAL = 3000;
xss.NETCODE_SYNC_MS = 500;

xss.UPDATE_ERR_GAP = 1;
xss.UPDATE_ERR_NO_COMMON = 2;
xss.UPDATE_ERR_MISMATCHES = 3;
xss.UPDATE_SUCCES = 4;

xss.SCORE_LEADING = 1;
xss.SCORE_NEUTRAL = 2;
xss.SCORE_BEHIND = 3;

xss.SPAWN_APPLE = 1;
xss.SPAWN_POWERUP = 2;

xss.NOTICE_CRASH = 1;
xss.NOTICE_JOIN = 2;
xss.NOTICE_DISCONNECT = 3;
xss.NOTICE_NEW_ROUND = 4;
