name: Test

on:
  push:
    paths:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Node 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
